title: Happy Kitten
author: Rohit Yadav
email: rohit@yadav.cloud
description: >
  This site celebrates life of a beloved kitten named Happy. Adopt don't shop.

baseurl: ""
url: https://happykitten.in

timezone: Asia/Kolkata
encoding: "utf-8"

permalink: stories/:categories/:title/

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
